version: '3.8'

services:
  dbtestusers:
    image: pgvector/pgvector:pg18
    container_name: dbtestusers
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: project_farm
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  postgres_data: